
# This is the example configuration file for NetworkMonitor

# Defines how long we will wait before checking nodes again
SleepInterval: 120

# Checking to make sure we have a connection to the outside world
# You will want to place the nodes in the order that you want them tested
Nodes:
  - Name: LocalHost
    Address: 172.0.0.1
    Protocol: icmp
    Required: true
    Category: Local

  - Name: WAN
    Address: 192.168.0.1
    Protocol: icmp
    Required: true
    category: Local

  - Name: Google
    Address: google.com
    Protocol: icmp
    Required: false
    category: External

  - Name: Google
    Address: http://google.com
    protocol: http
    required: false
    category: External